
hw4: 
	g++ -Wall -c common.cpp
	g++ -Wall -c my570list.cpp
	g++ -Wall -c Room.cpp
	g++ -Wall -c Wall.cpp
	g++ -Wall -c MazeGenerator.cpp
	g++ -Wall -c MazeSolver.cpp
	g++ -Wall -c hw4.cpp
	g++ -Wall common.o hw4.o my570list.o Room.o Wall.o MazeGenerator.o MazeSolver.o -o hw4

clean: 
	rm -rf *.o *.gch hw4
